### ISSUE TITLE
自定义llm这里对azure支持不太友好，本想仿造openai.py编写，发现很多代码都写死了，建议使用openai库编写自定义llm，可以更好支持azure

### ISSUE THREAD

**Issue by ForgetThatNight** [Undertone0809/promptulate#282]

**Comment by Undertone0809** [comment]
Thanks your feedback! I want to rebuild BaseLLM implement so that we can custom LLM more easily. However, original BaseLLM use pydantic v1 to build. It introduces too much code style invasiveness, increasing development difficulty. 

In the future, I think we will remove Pydantic style and make it compatible with the original implementation style.

**Comment by Undertone0809** [comment]
You can implement Azure and it's best not to follow the openai.py implementation.

**Comment by ruanrongman** [comment]
I think so, it's best not to follow the openai.py implementation.

**Comment by Undertone0809** [comment]
ref: https://undertone0809.github.io/promptulate/#/modules/llm/custom_llm?id=custom-llm
